export type UserSchema = {
  id?: number;
  userId?: number;
  link?: string;
  pdf?: string;
  resume?: string;
  img?: string;
  fullName?: string;
  currentJob?: string;
  email?: string;
  currentCompany?: string;
  disabled?: boolean;
  favFolderId?: number;
  isFavoris?: boolean;
  createdAt?: string;
  updatedAt?: string;
  locked?: boolean;
  deleted?: boolean;
  count?: string;
};
