name: Notify Discord on Column Move in @profiilo Project

on:
  project_card:
    types: [moved]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: github.repository == 'AlexandreScht/Profiilo'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch card details
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.inertia-preview+json" \
          "${{ github.event.project_card.url }}" > card_details.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse card details
        run: |
          CARD_NAME=$(jq -r '.content_url' card_details.json)
          echo "CARD_NAME=$CARD_NAME" >> $GITHUB_ENV
          PREVIOUS_COLUMN=$(jq -r '.project_card.previous_column_name' card_details.json)
          echo "PREVIOUS_COLUMN=$PREVIOUS_COLUMN" >> $GITHUB_ENV
          CURRENT_COLUMN=$(jq -r '.project_card.column_name' card_details.json)
          echo "CURRENT_COLUMN=$CURRENT_COLUMN" >> $GITHUB_ENV

      - name: Notify Discord
        uses: Ilshidur/action-discord@v2
        with:
          args: "Card ${CARD_NAME} : ${PREVIOUS_COLUMN} -> ${CURRENT_COLUMN}"
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
